/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luismendoza.project15_1;

import com.fazecast.jSerialComm.SerialPort;
import com.fazecast.jSerialComm.SerialPortDataListener;
import com.fazecast.jSerialComm.SerialPortEvent;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.IOException;
import java.io.OutputStream;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author luis-mendoza
 */
public class Project15_1 extends javax.swing.JFrame {
    SerialPort serialPort1;
    OutputStream outputStream1;
    SerialPort commPorts[];
    Boolean isPortOpen = false;
    Boolean isSequenceOn = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Project15_1.class.getName());

    /**
     * Creates new form Project15_1
     */
    public Project15_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Project 15.1 7-Segment Display");

        jLabel2.setText("COM Ports:");

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });

        jButton1.setText("Open Port");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Start Sequence");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        commPorts = SerialPort.getCommPorts();
        jComboBox1.removeAllItems();
        
        for (SerialPort commPort : commPorts)
            jComboBox1.addItem(commPort.getSystemPortName() + " - " + commPort.getDescriptivePortName());
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    void fillLeds(boolean[] number, JButton[] leds) {
        for (int j = 0; j < leds.length; j++) {
            if (number[j] == true) leds[j].setBackground(Color.red);
            else leds[j].setBackground(Color.white);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JButton[] leds = {jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9};
        boolean[] _0 = {true, true, true, true, true, true, false};
        boolean[] _1 = {false, true, true, false, false, false, false};
        boolean[] _2 = {true, true, false, true, true, false, true};
        boolean[] _3 = {true, true, true, true, false, false, true};
        boolean[] _4 = {false, true, true, false, false, true, true};
        boolean[] _5 = {true, false, true, true, false, true, true};
        boolean[] _6 = {true, false, true, true, true, true, true};
        boolean[] _7 = {true, true, true, false, false, false, false};
        boolean[] _8 = {true, true, true, true, true, true, true};
        boolean[] _9 = {true, true, true, true, false, true, true};
        boolean[] _10 = {true, true, true, false, true, true, true};
        boolean[] _11 = {false, false, true, true, true, true, true};
        boolean[] _12 = {true, false, false, true, true, true, false};
        boolean[] _13 = {false, true, true, true, true, false, true};
        boolean[] _14 = {true, false, false, true, true, true, true};
        boolean[] _15 = {true, false, false, false, true, true, true};
        
        if (!isPortOpen) {
            try {
                commPorts = SerialPort.getCommPorts();
                serialPort1 = commPorts[jComboBox1.getSelectedIndex()];
                serialPort1.setComPortParameters(9600, 8, 1, 0);

                serialPort1.addDataListener(new SerialPortDataListener() {
                    @Override
                    public int getListeningEvents() {return SerialPort.LISTENING_EVENT_DATA_RECEIVED;}

                    @Override
                    public void serialEvent(SerialPortEvent event)
                    {
                        String newData = new String(event.getReceivedData()); // Returns any raw data bytes associated with this serial port event.
                        
                        if (newData.contains("on")) {
                            String[] data = newData.split(",");
                            
                            try {
                                int number = Integer.parseInt(data[1]);
                                
                                switch (number) {
                                    case 0 -> fillLeds(_0, leds);
                                    case 1 -> fillLeds(_1, leds);
                                    case 2 -> fillLeds(_2, leds);
                                    case 3 -> fillLeds(_3, leds);
                                    case 4 -> fillLeds(_4, leds);
                                    case 5 -> fillLeds(_5, leds);
                                    case 6 -> fillLeds(_6, leds);
                                    case 7 -> fillLeds(_7, leds);
                                    case 8 -> fillLeds(_8, leds);
                                    case 9 -> fillLeds(_9, leds);
                                    case 10 -> fillLeds(_10, leds);
                                    case 11 -> fillLeds(_11, leds);
                                    case 12 -> fillLeds(_12, leds);
                                    case 13 -> fillLeds(_13, leds);
                                    case 14 -> fillLeds(_14, leds);
                                    case 15 -> fillLeds(_15, leds);
                                    default -> {
                                        for (int j = 0; j < leds.length; j++) leds[j].setBackground(Color.white);
                                    }
                                }
                            }
                            catch (Exception e) {
                                System.out.println(e);
                            }
                        }
                        else for (JButton led : leds) led.setBackground(Color.white);
                    }
                });
                
                if (serialPort1.getDescriptivePortName().contains("Pico")) {
                    serialPort1.setDTR();
                    serialPort1.setRTS();
                }
                
                serialPort1.openPort();

                if (serialPort1.isOpen()) {
                    JOptionPane.showMessageDialog(this, "The port was successfully opened!");
                    isPortOpen = serialPort1.isOpen();
                    jButton1.setText("Close Port");
                    jComboBox1.setEnabled(false);
                    jButton2.setEnabled(true);
                }
                else JOptionPane.showMessageDialog(this, "The port couldn't be opened!");
            }
            catch (ArrayIndexOutOfBoundsException a) {
                JOptionPane.showMessageDialog(this, "Select a COM port!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            try {
                serialPort1.closePort();
                JOptionPane.showMessageDialog(this, "The port was successfully closed!");
                isPortOpen = serialPort1.isOpen();
                jButton1.setText("Open Port");
                jComboBox1.setEnabled(true);
                jButton2.setEnabled(false);

                if (serialPort1.getDescriptivePortName().contains("Pico")) {
                    serialPort1.clearDTR();
                    serialPort1.clearRTS();
                }
            }
            catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        outputStream1 = serialPort1.getOutputStream();
        
        if (!isSequenceOn) {
            try {
                outputStream1.write("start\n".getBytes());
                isSequenceOn = true;
                jButton2.setText("Stop Sequence");
                jButton1.setEnabled(false);
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            try {
                outputStream1.write("stop\n".getBytes());
                isSequenceOn = false;
                jButton2.setText("Start Sequence");
                jButton1.setEnabled(true);
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (isPortOpen) {
            try {
                outputStream1.write("stop\n".getBytes());
                serialPort1.closePort();
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Project15_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
